"""create market data table

Revision ID: b20c4005dd17
Revises: 
Create Date: 2026-09-26 16:25:04.616205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b20c4005dd17'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('price_change', sa.Float(), nullable=True),
    sa.Column('price_change_percent', sa.Float(), nullable=True),
    sa.Column('trading_range', sa.Float(), nullable=True),
    sa.Column('average_volume', sa.Float(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('relative_volume', sa.Float(), nullable=True),
    sa.Column('buying_pressure', sa.Float(), nullable=True),
    sa.Column('selling_pressure', sa.Float(), nullable=True),
    sa.Column('momentum', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'datetime', name='uq_market_data_symbol')
    )
    op.create_index(op.f('ix_market_data_datetime'), 'market_data', ['datetime'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_datetime'), table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
